services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: "mongodb://host.docker.internal:27017/codemeet"
      PORT: "3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend